- name: terraform
  terraform:
    project_path: './aws-terraform'
    state: present
    force_init: yes
  register: tf_aws
- name: master
  add_host:
    name: '{{ tf_aws.outputs.public1.value }}'
    groups: k8s-master
- name: workers 1
  add_host:
    name: '{{ tf_aws.outputs.public2.value }}'
    groups: k8s-workers
    K8S_MASTER_NODE_IP: '{{ tf_aws.outputs.private1.value }}'
- name: workers 2
  add_host:
    name: '{{ tf_aws.outputs.public3.value }}'
    groups: k8s-workers
- name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
  wait_for:
    port: 22
    host: '{{ tf_aws.outputs.public1.value }}'
    delay: 10
  connection: local
- name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
  wait_for:
    port: 22
    host: '{{ tf_aws.outputs.public2.value }}'
    delay: 10
  connection: local
- name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
  wait_for:
    port: 22
    host: '{{ tf_aws.outputs.public3.value }}'
    delay: 10
  connection: local